[package]
name = "testgtkbutton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.16.2"
gio = "0.16.7"
glib ="0.16.7"
gdk = "0.13.2"
